// ReedSolomonVersion.hpp
// Generated by CMake

namespace NReedSolomon
{
const int32_t RS_VERSION_MAJOR = @ReedSolomon_VERSION_MAJOR@;
const int32_t RS_VERSION_MINOR = @ReedSolomon_VERSION_MINOR@;
const int32_t RS_VERSION_PATCH = @ReedSolomon_VERSION_PATCH@;
const std::string RS_VERSION_STRING = "v@ReedSolomon_VERSION@";

const std::string RS_APP_CMAKE_NAME = "@PROJECT_NAME@";
const std::string RS_APP_CMAKE_DESCRIPTION = "@ReedSolomon_DESCRIPTION@";
};
