// ReedSolomonVersion.hpp
// Generated by CMake
#pragma once

namespace NReedSolomon
{
    constexpr int32_t RS_VERSION_MAJOR = 1;
    constexpr int32_t RS_VERSION_MINOR = 0;
    constexpr int32_t RS_VERSION_PATCH = 0;
    const std::string RS_VERSION_STRING = "v1.0.0";

    const std::string RS_APP_CMAKE_NAME = "ReedSolomon";
    const std::string RS_APP_CMAKE_DESCRIPTION = "ReedSolomon error correction library";
}